version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
    environment:
      - GO_DOCKER_PORT=$GO_DOCKER_PORT
      - GO_LOCAL_PORT=$GO_LOCAL_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - SSL_MODE=$SSL_MODE
    ports:
      - $GO_LOCAL_PORT:$GO_DOCKER_PORT
    volumes:
      - ./server:/app
    env_file:
      - ./.env

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - api
      - client
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    restart: always

  postgres:
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
    image: postgres:latest
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./database/postgresql.conf:/etc/postgresql.conf
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - /pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
